eshareh_final/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('word/', include('word.urls')),
    path('interest/', include('users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
               static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
app_name='users'
urlpatterns = [
    path("list_interest_user/", views.list_interest_user, name='list_interest_user'),
    path("add_word_to_interest/<slug:slug>/", views.add_word_to_interest, name='add_word_to_interest'),
    path("profile/", views.profile, name='profile'),
    path("login/", views.user_login, name='login'),

]

word/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("word/", views.word, name='word_list'),
    path("word/<slug:slug>/", views.word, name='word_detail'),
    path("category/", views.category, name='category-list'),
    path("category/<slug:slug>/", views.category, name='category_detail'),
    path("exam/", views.random_word_exam, name='random_word_exam'),
    path("true/", views.true_exam, name='true_exam'),
    path("false/", views.false_exam, name='false_exam'),
    path("search/", views.search, name='search'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import re

from word.models import Word
# Create your models here.


class CustomUser(AbstractUser):
    first_name = models.CharField(null=True, blank=True, max_length=155, verbose_name='نام')
    last_name = models.CharField(null=True, blank=True, max_length=155, verbose_name='نام خانوادگی')
    username = models.CharField(max_length=15, unique=True, verbose_name="شماره موبایل")
    is_vip = models.BooleanField(default=False, verbose_name="نوع کاربر")
    picture = models.ImageField(null=True, blank=True, upload_to="images", verbose_name="عکس پروفایل")

    def is_valid_iranian_mobile(self):
        pattern = r'^09[0-9]{9}$'
        return re.match(pattern, self.username)

    def clean(self):
        super().clean()
        if not self.is_valid_iranian_mobile():
            raise ValidationError({'username': 'شماره موبایل وارد شده معتبر نمی‌باشد.'})

    def __str__(self):
        return str(self.first_name) + str(self.last_name)


class Interest(models.Model):
    word = models.ManyToManyField(Word, verbose_name='کلمه', related_name='CustomUser')
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, verbose_name='کاربر', related_name='Interest')

word/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='عنوان')
    slug = models.CharField(max_length=255, verbose_name='اسلاگ')
    picture = models.ImageField(upload_to='images', verbose_name='عکس')
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, verbose_name='والدین', related_name='children',null=True,blank=True)

    def __str__(self):
        return self.title


class Word(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')
    picture = models.ImageField(upload_to='images', verbose_name='عکس')
    video = models.FileField(upload_to='film', verbose_name='فیلم')
    pronunciation = models.CharField(max_length=50, verbose_name='تلفظ')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL,null=True,blank=True)
    slug = models.CharField(max_length=255, verbose_name='اسلاگ')

    def __str__(self):
        return self.title

users/views.py
# from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Interest
from .models import Word


# Create your views here.
@login_required
def list_interest_user(request, slug=None):
    interest = Interest.objects.filter(user=request.user).first()
    word = interest.word.all()
    return render(request, 'favorite.html', {'words': word})

@login_required
def add_word_to_interest(request, slug):
    word = get_object_or_404(Word, slug=slug)  # Omid
    interest, created = Interest.objects.get_or_create(user=request.user)  # (obj, False)
    if word not in interest.word.all():
        interest.word.add(word)
        return HttpResponse("added word to bookmark")
    else:
        interest.word.remove(word)
        return HttpResponse("remove as bookmark")

@login_required
def profile(request):
    # context=CustomUser.objects.get(pk=request.user.pk)
    return render(request, 'profile_user.html', {'context': request.user})


def user_login(request):
    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = authenticate(username=username, password=password)
        if user is not None:
            # Save session as cookie to login the user
            login(request, user)
            # Success, now let's login the user.
            return HttpResponse("ok")
        else:
            # Incorrect credentials, let's throw an error to the screen.
            return render(request, 'login.html', {'error_message': 'Incorrect username and / or password.'})
    else:
        # No post data availabe, let's just show the page to the user.
        return render(request, 'login.html')

word/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
import random

from users.models import Interest
from .models import Word, Category
from django.http.response import HttpResponse


@login_required
# Create your views here.
def word(request, slug=None):
    word_interest = get_object_or_404(Word, slug=slug)
    if word_interest in Interest.objects.get(user=request.user).word.all():
        has_word = True
    else:
        has_word = False
    return render(request, 'word.html', {"word": word_interest, "word_interest": has_word})


@login_required
def category(request, slug=None):
    queryset = Category.objects.filter(parent__isnull=True)
    if slug:
        parent = get_object_or_404(Category, slug=slug)
        queryset = Category.objects.filter(parent=parent)
    if not queryset:
        category = get_object_or_404(Category, slug=slug)
        queryset = Word.objects.filter(category=category)
        return render(request, 'word_list.html', {'words': queryset})

    return render(request, 'category.html', {'categories': queryset})


@login_required
def random_word_exam(request):
    random_word = random.choices(Word.objects.all(), k=4)
    selected_one_word = random.sample(random_word, k=1)
    context = {
        'random_word': random_word,
        'selected_one_word': selected_one_word[0],
    }
    return render(request, 'random.html', context)


@login_required
def true_exam(request):
    return HttpResponse("T")


@login_required
def false_exam(request):
    return HttpResponse("F")


@login_required
def search(request):
    if request.method == "POST":
        searched = request.POST['searched']
        words = Word.objects.filter(title__icontains=searched)
        return render(request, 'result.html', {'searched': searched, 'words': words})
    else:
        return render(request, 'result.html', {})

users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>MyDjangoApp</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body class="override">
<nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/mymodule/">MyDjangoApp</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/mymodule/login">Login</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        {% block content %}{% endblock %}
    </div>
</div>

<footer>
    <div class="container">
        <div class="row well ml-t">
            <div class="col-lg-8 col-md-8">
                <h4>Developed by: <a href="https://carlofontanos.com" target="_blank">Carl Victor C. Fontanos</a></h4>
            </div>
            <div class="col-lg-4 col-md-4">
                <p class="m-t">Copyright &copy <a href="https://carlofontanos.com"
                                                  target="_blank">www.carlofontanos.com</a> 2017</p>
                <p>All Rights Reserved.</p>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

users/templates/favorite.html
<h1>List favorite me</h1>
{% for word in words %}
    <a href="{% url 'word_detail' word.slug %}">{{ word.title }}</a>
{% endfor %}

users/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Login</div>
                    <div class="panel-body">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                        <div class="form-group clearfix">
                            <label for="username" class="col-md-4 control-label text-right">Username:</label>
                            <div class="col-md-6">
                                <input name="username" value="" type="text" class="form-control"/>
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="password" class="col-md-4 control-label text-right">Password:</label>
                            <div class="col-md-6">
                                <input name="password" type="password" class="form-control"/>
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input name="login" type="submit" value="Login" class="btn btn-success"/> &nbsp;
                            <a href="/mymodule/register">or Register</a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/profile_user.html
<center>
    {% if user.picture %}
        <img src="{{ user.picture.url }}" alt="" height="300" width="300">
    {% endif %}
    <h1>{{ user.first_name }}</h1>
    <h2>{{ user.last_name }}</h2>
    <p>{{ user.is_vip }}</p>
    <p>{{ user.username }}</p>
</center>

word/templates/category.html
{% for cat in categories %}
    <button>
    <a href="{% url 'category_detail' cat.slug %}">{{ cat.title }}</a>
        <br>
        <br>
        <br>
        <br>
    <img src="{{ cat.picture.url }}" alt="alt" width="350" height="350">
    </button>
{% endfor %}

word/templates/random.html
<center>
    {% for word in  random_word %}
        {% if selected_one_word == word %}
            <a href="{% url 'true_exam' %}">{{ word.title }}</a>
        {% else %}
            <a href="{% url 'false_exam' %}">{{ word.title }}</a>
        {% endif %}
    {% endfor %}
    <img src="{{ selected_one_word.picture.url }}" alt="" width="300" height="300">
</center>

word/templates/result.html
{% if searched %}
    <h1>you searched for {{ searched }}</h1>
    <br>
    {% for word in words %}
        <a href="{% url 'word_detail' word.slug %}">{{ word.title }}</a>
    {% endfor %}
{% else %}
    <h1> hey you forgot to search for a word</h1>
{% endif %}

word/templates/search.html
<form  method=Post
action="{% url 'search' %}">
    {% csrf_token %}
    <input type="search" placeholder="search words" aria-label="search" name="searched">
    <button type="submit">search
    </button>
</form>

word/templates/word.html
<center>
    <h1>{{ word.title }}</h1>
    <p>{{ word.pronunciation }}</p>
    <img src="{{ word.picture.url }}" alt="{{ word.title }}" width="350" height="350">
    <video src="{{ word.video.url }}" height="350" width="350" autoplay="autoplay" controls="controls"></video>
    {% if word_interest %}
        <button type="button"><a href="{% url 'users:add_word_to_interest' word.slug %}">Delete</a></button>
    {% else %}
        <button type="button"><a href="{% url 'users:add_word_to_interest' word.slug %}">Add</a></button>
    {% endif %}
</center>

word/templates/word_list.html
{% for word in words %}
    <a href="{% url 'word_detail' word.slug %}">{{ word.title }}</a>
{#    <h1>{{ word.title }}</h1>#}
{% endfor %}